server:
  port: 8000
spring:
  thymeleaf:
      mode: HTML5
      encoding: UTF-8
      cache: false
      suffix: .html
      enabled: true
      servlet:
        content-type: text/html
      check-template: true
      check-template-location: true
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      publisher-confirms: true
      virtual-host: /
  datasource:
      name: mydb
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: 654321
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  aop:
    proxy-target-class: true
mybatis:
  mapperLocations: classpath:/mapping/*.xml
  typeAliasesPackage: com.kxll.entity
  configLocation: classpath:/mybatis-config.xml