spring: 
  datasource:  
    name: mydb  
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/oauth2  
    username: root  
    password: 654321  
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20 
    
  redis:
    host: localhost
    password: 
    port: 6379
    pool: 
      max-idle: 100
      min-idle: 1
      max-active: 100
      max-wait: -1
server:
  port: 8888